### PR TITLE
Fix/1307/mqtt simulator causes warnings in mqtt kafka bridge

### LINKED ISSUE #1307: MQTT simulator causes warnings in mqtt-kafka-bridge
### Expected Behavior

There should be no warnings.

### Current Behavior

There are warnings

### Relevant log output

```shell
{"log.level":"warn","@timestamp":"2022-10-12T16:32:57.804Z","log.origin":{"file.name":"mqtt-kafka-bridge/kafka.go","file.line":112},"message":"kafkaToQueue [INVALID] message not forwarded because the content is not a valid JSON%!(EXTRA string=^ia.+,
```

### Steps to Reproduce

1. Install UMH
2. ?
3. Profit

### Context (Environment)

Playing around with the installation

### Possible Solution

ia/raw messages (or the new equivalent) should be always forwarded, independent of the payload. All the other messages should be valid JSON.

### Version

v0.9.x

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Scarjit**
# Description

This pr allows raw to pass trough mqtt-kafka-bridge and includes strikter checks for everything else.

Fixes #1307 

This pr is against the epic branch, to use it's new topic parser

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [X] The parser was tested

# Checklist:

- [ ] I have made corresponding changes to the documentation
- [x] I have made corresponding changes to the changelog (if needed).

### CODE REVIEW

File: golang/cmd/kafka-to-postgresql/pxProcessValue.go [hunk 1]
```diff
@@ -204,12 +204,12 @@ func writeProcessValueToDatabase(messages []*kafka.Message) (
 
 					// This function can parse any float, int and bool values.
 					// It will discard any other values with a warning.
-					switch v.(type) {
+					switch vX := v.(type) {
```
Comment (Scarjit) [inline golang/cmd/kafka-to-postgresql/pxProcessValue.go:207]: This is also in the epic branch, not sure why it still shows up here
