### PR TITLE
Fix/1404/factoryinsight returns thousands of duplicate values

### LINKED ISSUE #1404: factoryinsight returns thousands of duplicate values
### Expected Behavior

factoryinsight should only send values, if the value came from the DB or was produced by LOCF/Interpolate

### Current Behavior

factoryinsight returns thousand of datapoints, even if they contain the same data, and have no db backing.

### Relevant log output

_No response_

### Steps to Reproduce

1) Install latest step
2) Use v2 datasource to query any datapoint

### Context (Environment)

Customer

### Possible Solution

_No response_

### Version

v0.9.x

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Scarjit**
# Description

This pr checks if a datapoint only contains null values, and if so, skips it.

Fixes #1404 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: golang/cmd/factoryinsight/v2/services/service-tree.go [hunk 1]
```diff
@@ -345,10 +345,10 @@ func GetCustomTagsTree(
 		// ignore underscores at the beginning or end of the tag or if there are multiple underscores in a row
 		sanitizedSplitTag := removeEmpty(splitTag)
 		// remove unused capacity to save memory
-		sanitizedSplitTag = slices.Clip(sanitizedSplitTag)
+		sanitizedSplitTag = slices.Clip(sanitizedSplitTag) // WTF is this?
```
Comment (DaruZero) [inline golang/cmd/factoryinsight/v2/services/service-tree.go:348]: Removes unused capacity from the slice, to save a little bit of memory. I thought it wouldn't hurt
